---
- name: Update the web servers
  hosts: 127.0.0.1
  vars_files:   
   - vars/variables.yaml
  tasks:
   - name: Create the folder
     file:
      path: "{{ folder }}"
      owner: "{{ owner }}"
      state: directory
      become: yes
      become_method: sudo
